exp_name: detectron2_test
seed: 999
train_annotation: 'train.json'
test_annotation: 'test.json'
dataset_root: '../dataset/'

num_classes: 10

parameters:
  batch_size_per_image: 128
  ims_per_batch: 4
  base_lr: 0.001
  max_iter: 1000
  steps: [8000, 12000]
  gamma: 0.005
  checkpoint_period: 3000
  eval_period: 3000
  score_thresh_test: 0.3


transform:
  augmentations:
    - type: RandomFlip
      params:
        prob: 0.5
        horizontal: False
        vertical: True
    - type: RandomBrightness
      params:
        intensity_min: 0.8
        intensity_max: 1.8
    - type: RandomContrast
      params:
        intensity_min: 0.6
        intensity_max: 1.3

device: 'cuda'

output_dir: './output/detectron2'

model_type: 'detectron2'
model_name: 'faster_rcnn_R_101_FPN_3x.yaml'
model_url: 'COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml'
pretrained: true