exp_name: mmdetection_test
seed: 999
train_annotation: 'train.json'
test_annotation: 'test.json'
dataset_root: '../dataset'

classes: ["General trash", "Paper", "Paper pack", "Metal", "Glass", 
    "Plastic", "Styrofoam", "Plastic bag", "Battery", "Clothing"]

device: 'cuda'

work_dir: './output/mmdetection'

model_type: 'mmdetection'
model_name: 'faster_rcnn_r50_fpn_1x'
model_dir: './MMdetection/models/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.py'
pretrained: true