exp_name: torch_test
seed: 999
train_annotation: ../dataset/train.json
test_annotation: ../dataset/test.json
data_dir: '../dataset'

num_classes: 10
score_threshold: 0.05

transform:
  augmentations:
    - type: Resize
      params:
        height: 1024
        width: 1024
    - type: Flip
      params:
        p: 0.5

device: 'cuda'

model_type: 'torchvision'
model_name: 'fasterrcnn_resnet50_fpn'
pretrained: true

optimizer:
  type: SGD
  params:
    lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005

epoch: 5
train_batch_size: 16
test_batch_size: 8
output_dir: './output/faster_rcnn_output/'